baseURL = "https://focusuy.netlify.app/"
title = "FOCUS"
author = "username"
languageCode = "es"
DefaultContentLanguage = "es"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true


# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "FOCUS Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "FOCUS"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true
    plugins_css = ["custom"]

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "FOCUS"
    meta_og_type = "website"
    meta_og_url = "https://focusuy.org"
    meta_og_image = ""
    meta_og_description = "FOCUS"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "sobre"
    name = "Quiénes somos"
    url = "/sobre/"
    weight = 1

  [[menu.main]]
    identifier = "Servicios"
    name = "Servicios"
    url = "/servicios/"
    weight = 2

  [[menu.main]]
    identifier = "Equipo"
    name = "Equipo"
    url = "/equipo/"
    weight = 3
    
  [[menu.main]]
    identifier = "clientes"
    name = "Clientes"
    url = "/clientes/"
    weight = 4

  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    url = "/contacto/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "(+598) 92 463 402"
    url = ""
      weight = 1

  [[menu.footer]]
    name = "contacto@focusuy.org"
    url = "contacto@focusuy.org"
    pre = ""
      weight = 2
  
  [[menu.footer]]
    name = "Razón Social: GONZALEZ GONZALEZ SARA VICTORIA / RUT 218716500014"
    url = ""
    pre = ""
      weight = 3
      
  [[menu.footer]]
    name = "Dir: Lavalleja 764, Montevideo, Uruguay"
    url = ""
    pre = ""
      weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
