baseURL: ""
theme: "up-business-theme"
languageCode: "en-us"

title: ""

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Focus"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/mvd.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    github: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Montevideo, Uruguay"
    
  contact:
    - "contacto@focusuy.org"
    - "xxx.yyy.zzz"

  
menus:
  main:
    - name: "Inicio"
      url: "/#hero"
      weight: 1

    - name: "Servicios"
      url: "/#services"
      weight: 2

    - name: "Equipo"
      url: "/#"
      weight: 3

    - name: "Clientes"
      url: "/#brands"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5
      
    - name: "Contacto"
      url: "/contacto"
      weight: 6


  footer:
    - name: "Inicio"
      url: "/#hero"
      weight: 1

    - name: "Servicios"
      url: "/#services"
      weight: 2

    - name: "Equipo"
      url: "/#"
      weight: 3

    - name: "Clientes"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
